version: "3.2"
services:
  server:
    build: server/
    command: python ./server.py
    ports:
      - "3000:3000"
    networks:
      - my-network
    restart: always
  client:
    build: client/
    command: python ./client.py
    ports:
      - "9000:9000"
    networks:
      - my-network
    depends_on:
      - server
    restart: always
networks:
  my-network:
    driver: bridge